### ISSUE TITLE
Name Confusion

### ISSUE THREAD

**Issue by cdrnet** [MachineCognitis/C.math.NET#1]
Thanks a lot for putting this together and make it available here on GitHub and on NuGet! I might have some use for this myself in the future.

I'm opening this issue because I've been contacted by someone wondering whether C.math.NET is related to [Math.NET](https://www.nuget.org/packages/MathNet.Numerics/), one of the major open source math library projects in the .Net space, which I maintain for more than 15 years by now. To avoid further confusion on both sides e.g. when searching for NuGet packages, I wonder whether it might be an option for you to change the name of your library and NuGet packages very slightly such that it would no longer contain the string "math.net" (nor "mathnet")? C.math.NET seems to be just a few days old, so it might still be possible without too much damage. If not then that's fine, but I think it was worth to ask, as it would seem beneficial for both of us :).

Thanks,
Christoph

**Comment by MachineCognitis** [comment]
Good point. I changed the title of the NuGet package to "C math (in .NET)" following the same idea of at least one other math .NET package not related to the Math.NET packages collection.

**Comment by cdrnet** [comment]
Great, thanks a lot!
